import type { Metadata } from "next";
import "../styles/globals/globals.css";

// Root layout for Next.js App Router
export const metadata: Metadata = {
    title: "FACK",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}